### ISSUE TITLE
trig function with argument of form I*x

### ISSUE THREAD

**Issue by rwst** [pynac/pynac#155]
Check if argument has the factor `I` and if so transform into the corresponding hyperbolic form, e.g.

```
sage: sin(2*I*x+I)
I*sinh(2*x+1)
```

This might be a border case where we want the functionality in a rewrite function. However, it's clearly a simplification, and SymPy does it immediately.

**Comment by behackl** [comment]
Should this be simplified in all cases, or just if x is known to be real?

**Comment by rwst** [comment]
What does mathematics say about it?

**Comment by behackl** [comment]
Mathematics doesn't really matter, the identity holds anyways.

I was asking more from a point of implementation, because in case we would only simplify for real x, we could work with `x.imag_part()` and implement this without much pain. Otherwise we'd have to think how to get the coefficient of `I`.

**Comment by rwst** [comment]
Try it so, please.
