### ISSUE TITLE
soname bump from 0.7.4 to 0.7.5

### ISSUE THREAD

**Issue by isuruf** [pynac/pynac#242]
I didn't expect a soname (`libpynac.so.9` to `libpynac.so.10`)  bump between a patch level increase. Was this intentional?

**Comment by rwst** [comment]
It seems the reason is that I didn't increment `lt_age` in 4417e6d7ce003b70cfc2. Would it be problematic to increase later or will we just have to live with it?

**Comment by isuruf** [comment]
I think we'll just have to live with it. @kiwifb, thoughts?

**Comment by kiwifb** [comment]
Just live with it. I am not sure if pynac follow any special rules for release numbers. A change of soname should reflect a change in API. I always considered all pynac releases API snowflakes because you usually need the precise release of pynac matching your version of sage. I would be happy to be wrong but I don't have the tools or time to do that kind of testing.

**Comment by isuruf** [comment]
> I always considered all pynac releases API snowflakes because you usually need the precise release of pynac matching your version of sage

Good to know
