### ISSUE TITLE
pynac 0.7.20 -- cmatcher.h missing?

### ISSUE THREAD

**Issue by SnarkBoojum** [pynac/pynac#329]
Trying to update Debian's package to 0.7.20, cmatcher.h doesn't seem to be in the tarball...

**Comment by rwst** [comment]
It's in the bz2 tarball.

**Comment by SnarkBoojum** [comment]
It's not in the gz tarball.

**Comment by rwst** [comment]
@SnarkBoojum Using a pynac version newer than in Sage develop is only supported if you use the respective Sage upgrade ticket branch, i.e. https://trac.sagemath.org/ticket/24838. Upgrade tickets also always have a link to the tarball that needs to be put into `upstream/`.

**Comment by SnarkBoojum** [comment]
I don't understand what you're talking about : I saw a new pynac published, tried to package it and failed because the [tarball](https://github.com/pynac/pynac/archive/pynac-0.7.20.tar.gz) is for some reason missing a file.

**Comment by rwst** [comment]
github makes default tarballs, don't use these, use the one I created with `make dist`, this: https://github.com/pynac/pynac/releases/download/pynac-0.7.20/pynac-0.7.20.tar.bz2

Also, pynac is not an independent library. Every pynac version up to 0.7.16 is asocciated with a specific Sage version. Newer versions need the upgrade ticket branch, as already said. You are lucky that the interface did not change since 0.7.16 (which is the one supported with the Sage `develop` branch).

**Comment by rwst** [comment]
I created https://github.com/pynac/pynac/wiki/Packaging-Pynac%3F and added it to the distributed files.

**Comment by SnarkBoojum** [comment]
The fact that github's tarball doesn't have one of the files is still the indication that something is amiss, and still needs to be fixed.

**Comment by rwst** [comment]
Why not have a look at https://github.com/pynac/pynac/commits/master?

**Comment by rwst** [comment]
Not strange. I simply forgot to `git add ginac/cmatcher.h` before doing the checkin.

**Comment by SnarkBoojum** [comment]
Hence the report about something missing...
